from setuptools import setup

setup(
    name='osu-performance',
    version='',
    packages=['env.Lib.site-packages.idna', 'env.Lib.site-packages.aiohttp', 'env.Lib.site-packages.certifi',
              'env.Lib.site-packages.chardet', 'env.Lib.site-packages.chardet.cli', 'env.Lib.site-packages.discord',
              'env.Lib.site-packages.discord.ext', 'env.Lib.site-packages.discord.ext.ipc',
              'env.Lib.site-packages.discord.ext.commands', 'env.Lib.site-packages.urllib3',
              'env.Lib.site-packages.urllib3.util', 'env.Lib.site-packages.urllib3.contrib',
              'env.Lib.site-packages.urllib3.contrib._securetransport', 'env.Lib.site-packages.urllib3.packages',
              'env.Lib.site-packages.urllib3.packages.backports',
              'env.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'env.Lib.site-packages.requests',
              'env.Lib.site-packages.multidict', 'env.Lib.site-packages.websockets',
              'env.Lib.site-packages.websockets.py35', 'env.Lib.site-packages.async_timeout',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.idna',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pytoml',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.certifi',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet.cli',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.msgpack',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.util',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib._securetransport',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.backports',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.colorama',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.lockfile',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.progress',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.requests',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.packaging',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.webencodings',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.req',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.vcs',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.utils',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.models',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.commands',
              'env.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.operations'],
    url='',
    license='',
    author='Duncan',
    author_email='',
    description=''
)
